name: C:\Users\jkr\Anaconda3\envs\warc
dependencies:
- backports_abc=0.4=py27_0
- blaze=0.9.1=py27_0
- bokeh=0.11.1=py27_0
- bzip2=1.0.6=vc9_2
- chest=0.2.3=py27_0
- cloudpickle=0.1.1=py27_0
- cytoolz=0.7.5=py27_0
- dask=0.8.1=py27_0
- datashape=0.5.1=py27_0
- decorator=4.0.9=py27_0
- enum34=1.1.2=py27_0
- flask=0.10.1=py27_1
- flask-cors=2.1.2=py27_0
- funcsigs=0.4=py27_0
- futures=3.0.3=py27_0
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=vc9_4
- heapdict=1.0.0=py27_0
- ipykernel=4.3.1=py27_0
- ipython=4.1.2=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=vc9_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.2.2=py27_0
- jupyter_console=4.1.1=py27_0
- jupyter_core=4.1.0=py27_0
- libpng=1.6.17=vc9_1
- libtiff=4.0.6=vc9_1
- llvmlite=0.9.0=py27_0
- locket=0.2.0=py27_0
- markupsafe=0.23=py27_0
- mistune=0.7.2=py27_0
- mkl=11.3.1=0
- msvc_runtime=1.0.1=vc9_0
- multipledispatch=0.4.8=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.11=py27_0
- notebook=4.1.0=py27_1
- numba=0.24.0=np110py27_0
- numexpr=2.4.6=np110py27_1
- numpy=1.10.4=py27_0
- odo=0.4.2=py27_0
- openssl=1.0.2g=vc9_0
- pandas=0.18.0=np110py27_0
- partd=0.3.2=py27_1
- path.py=8.1.2=py27_1
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_0
- psutil=4.1.0=py27_0
- pygments=2.1.1=py27_0
- pyqt=4.11.4=py27_5
- pyreadline=2.1=py27_0
- pytables=3.2.2=np110py27_1
- python=2.7.11=2
- python-dateutil=2.5.1=py27_0
- pytz=2016.2=py27_0
- pyyaml=3.11=py27_3
- pyzmq=15.2.0=py27_0
- qt=4.8.7=vc9_7
- qtconsole=4.1.1=py27_1
- requests=2.9.1=py27_0
- setuptools=20.3=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_2
- six=1.10.0=py27_0
- sqlalchemy=1.0.12=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- toolz=0.7.4=py27_0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- ujson=1.35=py27_0
- werkzeug=0.11.4=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_2

